config/routes.rb
Rails.application.routes.draw do

  resources :flagged_items

  resources :charities

  resources :challenges do
    resources :donations
    resources :submissions
    resources :comments
  end

  resources :events do
    resources :donations
    resources :comments
  end

  devise_for :users, :controllers => { omniauth_callbacks: 'omniauth_callbacks' }
  match '/users/:id/finish_signup' => 'users#finish_signup', via: [:get, :patch], :as => :finish_signup
  root to: 'visitors#index'
end

app/models/event.rb
class Event < ActiveRecord::Base
  belongs_to :user
  has_many :comments
  has_many :suggestions
  has_many :donations
  has_many :donated_users, through: :donations, source: :user
  has_many :flags, as: :item, class_name: FlaggedItem
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]

  # GET /events
  # GET /events.json
  def index
    @events = Event.all
    @events = @events.where(user_id: params[:user_id]) if params[:user_id]
  end

  # GET /events/1
  # GET /events/1.json
  def show
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(event_params)
    @event.user_id = current_user.id

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:title, :description, :start_date, :end_date, :user_id, :cancelled_flag, :completed_flag)
    end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_form.html.haml
= form_for @event do |f|
  - if @event.errors.any?
    #error_explanation
      %h2= "#{pluralize(@event.errors.count, "error")} prohibited this event from being saved:"
      %ul
        - @event.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :title
    = f.text_field :title
  .field
    = f.label :description
    = f.text_area :description
  .field
    = f.label :start_date
    = f.datetime_select :start_date
  .field
    = f.label :end_date
    = f.datetime_select :end_date
  .actions
    = f.submit 'Save'

app/views/events/edit.html.haml
%h1 Editing event

= render 'form'

= link_to 'Show', @event
\|
= link_to 'Back', events_path

app/views/events/index.html.haml
.page-header
  %h1 Events

- @events.each do |event|
  .panel.panel-success
    .panel-heading
      = link_to event.title, event
      .pull-right
        = link_to "Edit", edit_event_path(event)
        = link_to 'Destroy', event, :method => :delete, :data => { :confirm => 'Are you sure?' }
    .panel-body= event.description
    .panel-footer
      Created By:
      = event.user.try(:name)
      - unless event.user == current_user
        .pull-right
          = link_to new_flagged_item_path(item_id: event.id, type: event.class), id: "event_#{event.id}" do
            %span{class: "glyphicon glyphicon-flag", style: "color: red", title: "Flag this event"}

%br

= link_to 'New Event', new_event_path, class: "btn btn-primary"

:javascript 
  $(function() {
    
  });

app/views/events/new.html.haml
%h1 New event

= render 'form'

= link_to 'Back', events_path

app/views/events/show.html.haml
%p#notice= notice

.page-header
  %h1
    = @event.title
    %small
      Created By:
      = @event.user.try(:name)

%p
  %b Description:
  = @event.description
%p
  %b Start date:
  = @event.start_date
%p
  %b End date:
  = @event.end_date

%h3 Comments
- @event.comments.each do |comment|
  %p= comment.comment

= form_for [@event, @event.comments.build] do |f|
  = f.text_area :comment

  %br/
  = f.submit "Save"

%p= link_to "Donate", new_event_donation_path(@event), class: "btn btn-primary"

= link_to 'Edit', edit_event_path(@event)
\|
= link_to 'Back', events_path