config/routes.rb
Rails.application.routes.draw do

  resources :flagged_items

  resources :charities

  resources :challenges do
    resources :donations
    resources :submissions
    resources :comments
  end

  resources :events do
    resources :donations
    resources :comments
  end

  devise_for :users, :controllers => { omniauth_callbacks: 'omniauth_callbacks' }
  match '/users/:id/finish_signup' => 'users#finish_signup', via: [:get, :patch], :as => :finish_signup
  root to: 'visitors#index'
end

app/models/donation.rb
class Donation < ActiveRecord::Base
  belongs_to :user
  belongs_to :event
  belongs_to :challenge
  has_many :charity_donations
  has_many :charities, through: :charity_donations
end

app/controllers/donations_controller.rb
class DonationsController < ApplicationController
  before_action :set_donation, only: [:show, :edit, :update, :destroy]

  # GET /donations
  # GET /donations.json
  def index
    @donations = Donation.all
  end

  # GET /donations/1
  # GET /donations/1.json
  def show
  end

  # GET /donations/new
  def new
    @donation = Donation.new
  end

  # GET /donations/1/edit
  def edit
  end

  # POST /donations
  # POST /donations.json
  def create
    @donation = Donation.new(donation_params)

    respond_to do |format|
      if @donation.save
        format.html { redirect_to @donation, notice: 'Donation was successfully created.' }
        format.json { render :show, status: :created, location: @donation }
      else
        format.html { render :new }
        format.json { render json: @donation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /donations/1
  # PATCH/PUT /donations/1.json
  def update
    respond_to do |format|
      if @donation.update(donation_params)
        format.html { redirect_to @donation, notice: 'Donation was successfully updated.' }
        format.json { render :show, status: :ok, location: @donation }
      else
        format.html { render :edit }
        format.json { render json: @donation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /donations/1
  # DELETE /donations/1.json
  def destroy
    @donation.destroy
    respond_to do |format|
      format.html { redirect_to donations_url, notice: 'Donation was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_donation
      @donation = Donation.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def donation_params
      params.require(:donation).permit(:challenge_id, :user_id, :event_id, :donation_amount)
    end
end

app/helpers/donations_helper.rb
module DonationsHelper
end

app/views/donations/_form.html.haml
= form_for @donation do |f|
  - if @donation.errors.any?
    #error_explanation
      %h2= "#{pluralize(@donation.errors.count, "error")} prohibited this donation from being saved:"
      %ul
        - @donation.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :challenge_id
    = f.number_field :challenge_id
  .field
    = f.label :user_id
    = f.number_field :user_id
  .field
    = f.label :event_id
    = f.number_field :event_id
  .field
    = f.label :donation_amount
    = f.text_field :donation_amount
  .actions
    = f.submit 'Save'

app/views/donations/edit.html.haml
%h1 Editing donation

= render 'form'

= link_to 'Show', @donation
\|
= link_to 'Back', donations_path

app/views/donations/index.html.haml
%h1 Listing donations

%table
  %tr
    %th Challenge
    %th User
    %th Event
    %th Donation amount
    %th
    %th
    %th

  - @donations.each do |donation|
    %tr
      %td= donation.challenge_id
      %td= donation.user_id
      %td= donation.event_id
      %td= donation.donation_amount
      %td= link_to 'Show', donation
      %td= link_to 'Edit', edit_donation_path(donation)
      %td= link_to 'Destroy', donation, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Donation', new_donation_path

app/views/donations/new.html.haml
%h1 New donation

= render 'form'

= link_to 'Back', donations_path

app/views/donations/show.html.haml
%p#notice= notice

%p
  %b Challenge:
  = @donation.challenge_id
%p
  %b User:
  = @donation.user_id
%p
  %b Event:
  = @donation.event_id
%p
  %b Donation amount:
  = @donation.donation_amount

= link_to 'Edit', edit_donation_path(@donation)
\|
= link_to 'Back', donations_path