config/routes.rb
Rails.application.routes.draw do

  resources :flagged_items

  resources :charities

  resources :challenges do
    resources :donations
    resources :submissions
    resources :comments
  end

  resources :events do
    resources :donations
    resources :comments
  end

  devise_for :users, :controllers => { omniauth_callbacks: 'omniauth_callbacks' }
  match '/users/:id/finish_signup' => 'users#finish_signup', via: [:get, :patch], :as => :finish_signup
  root to: 'visitors#index'
end

app/models/charity.rb
class Charity < ActiveRecord::Base
  has_many :charity_donations
  has_many :donations, through: :charity_donations
  has_one :address, as: :addressable, class_name: Address
end

app/controllers/charities_controller.rb
class CharitiesController < ApplicationController
  before_action :set_charity, only: [:show, :edit, :update, :destroy]

  # GET /charities
  # GET /charities.json
  def index
    @charities = Charity.all
  end

  # GET /charities/1
  # GET /charities/1.json
  def show
  end

  # GET /charities/new
  def new
    @charity = Charity.new
  end

  # GET /charities/1/edit
  def edit
  end

  # POST /charities
  # POST /charities.json
  def create
    @charity = Charity.new(charity_params)

    respond_to do |format|
      if @charity.save
        format.html { redirect_to @charity, notice: 'Charity was successfully created.' }
        format.json { render :show, status: :created, location: @charity }
      else
        format.html { render :new }
        format.json { render json: @charity.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /charities/1
  # PATCH/PUT /charities/1.json
  def update
    respond_to do |format|
      if @charity.update(charity_params)
        format.html { redirect_to @charity, notice: 'Charity was successfully updated.' }
        format.json { render :show, status: :ok, location: @charity }
      else
        format.html { render :edit }
        format.json { render json: @charity.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /charities/1
  # DELETE /charities/1.json
  def destroy
    @charity.destroy
    respond_to do |format|
      format.html { redirect_to charities_url, notice: 'Charity was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_charity
      @charity = Charity.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def charity_params
      params.require(:charity).permit(:name, :description, :website)
    end
end

app/helpers/charities_helper.rb
module CharitiesHelper
end

app/views/charities/_form.html.haml
= form_for @charity do |f|
  - if @charity.errors.any?
    #error_explanation
      %h2= "#{pluralize(@charity.errors.count, "error")} prohibited this charity from being saved:"
      %ul
        - @charity.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :description
    = f.text_area :description
  .field
    = f.label :website
    = f.text_field :website
  .actions
    = f.submit 'Save'

app/views/charities/edit.html.haml
%h1 Editing charity

= render 'form'

= link_to 'Show', @charity
\|
= link_to 'Back', charities_path

app/views/charities/index.html.haml
%h1 Listing charities

%table
  %tr
    %th Name
    %th Description
    %th Website
    %th
    %th
    %th

  - @charities.each do |charity|
    %tr
      %td= charity.name
      %td= charity.description
      %td= charity.website
      %td= link_to 'Show', charity
      %td= link_to 'Edit', edit_charity_path(charity)
      %td= link_to 'Destroy', charity, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Charity', new_charity_path

app/views/charities/new.html.haml
%h1 New charity

= render 'form'

= link_to 'Back', charities_path

app/views/charities/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @charity.name
%p
  %b Description:
  = @charity.description
%p
  %b Website:
  = @charity.website

= link_to 'Edit', edit_charity_path(@charity)
\|
= link_to 'Back', charities_path