config/routes.rb
Rails.application.routes.draw do

  resources :flagged_items

  resources :charities

  resources :challenges do
    resources :donations
    resources :submissions
    resources :comments
  end

  resources :events do
    resources :donations
    resources :comments
  end

  devise_for :users, :controllers => { omniauth_callbacks: 'omniauth_callbacks' }
  match '/users/:id/finish_signup' => 'users#finish_signup', via: [:get, :patch], :as => :finish_signup
  root to: 'visitors#index'
end

app/models/challenge.rb
class Challenge < ActiveRecord::Base
  belongs_to :user
  has_many :submissions
  has_many :comments
  has_many :donations
  has_many :charities, through: :donations
  has_many :flags, as: :item, class_name: FlaggedItem
  has_one :location, as: :addressable, class_name: Address

  accepts_nested_attributes_for :location, reject_if: :all_blank, allow_destroy: true

  enum challenge_type: [:online, :local]

  def pretty_location
    location.try(:formatted_location)
  end

  def pretty_address
    location.try(:formatted_address)
  end

  def formatted_times
    if end_date.present?
      "#{I18n.l(end_date, format: :pretty)}"
    elsif start_time.to_date == end_time.to_date
      "#{I18n.l(start_time, format: :short_with_date)} - #{I18n.l(end_time, format: :just_time)}"
    else
      "#{I18n.l(start_time, format: :short_with_date)} - #{I18n.l(end_time, format: :short_with_date)}"
    end
  end
end

app/controllers/challenges_controller.rb
class ChallengesController < ApplicationController
  before_action :set_challenge, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]

  # GET /challenges
  # GET /challenges.json
  def index
    @challenges = Challenge.all
    @challenges = @challenges.where(user_id: params[:user_id]) if params[:user_id]
  end

  # GET /challenges/1
  # GET /challenges/1.json
  def show
  end

  # GET /challenges/new
  def new
    @challenge = Challenge.new
    @challenge.build_location if @challenge.location.blank?
  end

  # GET /challenges/1/edit
  def edit
    @challenge.build_location if @challenge.location.blank?
  end

  # POST /challenges
  # POST /challenges.json
  def create
    @challenge = Challenge.new(challenge_params)
    @challenge.user_id = current_user.id

    respond_to do |format|
      if @challenge.save
        format.html { redirect_to @challenge, notice: 'Challenge was successfully created.' }
        format.json { render :show, status: :created, location: @challenge }
      else
        format.html { render :new }
        format.json { render json: @challenge.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /challenges/1
  # PATCH/PUT /challenges/1.json
  def update
    respond_to do |format|
      if @challenge.update(challenge_params)
        format.html { redirect_to @challenge, notice: 'Challenge was successfully updated.' }
        format.json { render :show, status: :ok, location: @challenge }
      else
        format.html { render :edit }
        format.json { render json: @challenge.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /challenges/1
  # DELETE /challenges/1.json
  def destroy
    @challenge.destroy
    respond_to do |format|
      format.html { redirect_to challenges_url, notice: 'Challenge was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_challenge
      @challenge = Challenge.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def challenge_params
      params.require(:challenge).permit(:challenge_type, :start_time, :end_time, :title, :description, :end_date, :user_id, location_attributes: [:id, :name, :line1, :line2, :city, :state, :zip, :country])
    end
end

app/helpers/challenges_helper.rb
module ChallengesHelper
end

app/views/challenges/_form.html.haml
= bootstrap_nested_form_for @challenge do |f|
  - if @challenge.errors.any?
    #error_explanation
      %h2= "#{pluralize(@challenge.errors.count, "error")} prohibited this challenge from being saved:"
      %ul
        - @challenge.errors.full_messages.each do |msg|
          %li= msg

  = f.select :challenge_type, Challenge.challenge_types.keys
  = f.text_field :title
  = f.text_area :description
  .local
    = f.datetime_local_field :start_time
    = f.datetime_local_field :end_time
  .online
    = f.date_field :end_date

  .local
    %h2 Location
    = f.fields_for_with_bootstrap :location do |af|
      = af.text_field :name
      = af.text_field :line1
      = af.text_field :line2
      = af.text_field :city
      = af.text_field :state
      = af.text_field :zip
      = af.text_field :country

  .actions
    = f.submit 'Save'

:javascript
  $(document).ready(function() {
    $('#challenge_challenge_type').change(function() {
      if($(this).val() == "online") {
        $('.online').show();
        $('.local').hide();
      } else {
        $('.online').hide();
        $('.local').show();
      }
    });
    $('#challenge_challenge_type').change();
  });

app/views/challenges/edit.html.haml
%h1 Editing challenge

= render 'form'

= link_to 'Show', @challenge
\|
= link_to 'Back', challenges_path

app/views/challenges/index.html.haml
.page-header
  %h1 Challenges

- @challenges.each do |challenge|
  .panel.panel-success
    .panel-heading
      .pull-right{style: "margin-top: 7px"}
        = link_to edit_challenge_path(challenge) do
          %span.glyphicon.glyphicon-pencil{title: "Edit Challenge", style: "color: black;"}
        = link_to challenge, :method => :delete, :data => { :confirm => 'Are you sure?' } do
          %span.glyphicon.glyphicon-remove{title: "Remove Challenge", style: "color: red;"}
      %h3{style: "margin-top: 5px; margin-bottom: 5px"}
        = link_to challenge.title, challenge
        %small= challenge.formatted_times
    .panel-body= challenge.description
    .panel-footer
      %b Created By:
      = challenge.user.try(:name)
      - unless challenge.user == current_user
        .pull-right
          = link_to "Flag", new_flagged_item_path(item_id: challenge.id, type: challenge.class)

%br

= link_to 'New Challenge', new_challenge_path, class: "btn btn-primary"

app/views/challenges/new.html.haml
%h1 New challenge

= render 'form'

= link_to 'Back', challenges_path

app/views/challenges/show.html.haml
%p#notice= notice

.page-header
  %h1
    = @challenge.title
    %small
      Created By:
      = @challenge.user.try(:name)

%p
  %b Challenge Type:
  = @challenge.challenge_type
%p
  %b Description:
  = @challenge.description

- if @challenge.online?
  %p
    %b End date:
    = @challenge.end_date

- if @challenge.local?
  %p
    %b Start Time:
    = @challenge.start_time.localtime
  %p
    %b End Time:
    = @challenge.end_time.localtime

  %h3 Location
  = simple_format @challenge.pretty_location


%h3 Comments
- @challenge.comments.each do |comment|
  %p= comment.comment

= form_for [@challenge, @challenge.comments.build] do |f|
  = f.text_area :comment

  %br/
  = f.submit "Save"

%p= link_to "Donate", new_challenge_donation_path(@challenge), class: "btn btn-primary"

= link_to 'Edit', edit_challenge_path(@challenge)
\|
= link_to 'Back', challenges_path